### PR TITLE
chore: Simplify CI, allow merging of releases to main

### LINKED ISSUE #505: Error parsing the Package.swift file
## Description

Hello! I'm part of the [Swift Package Index](https://swiftpackageindex.com) team and was just trying to add this package to the index. We use `swift package dump-package` to extract package metadata in as JSON but when running that command for this package, the following error occurs:

```
$ xcrun swift package dump-package
/Users/dave/Desktop/aws-sdk-swift: error: manifest parse error(s):
main/Package.swift:104: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “release” doesn’t exist." UserInfo={NSFilePath=/Users/dave/Projects/Amplify/SwiftSDK/aws-sdk-swift/release, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x600000a28090 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
error: invalid manifests at [<AbsolutePath:"/Users/dave/Desktop/aws-sdk-swift">]
```

This is broken on `main` but works on the `0.1.0` tag. Unfortunately, to add the package to the index we need to be able to initially run the `dump-package` on a checkout of the default branch.

## Environment

* AWS Swift SDK version used: This is broken on `main` but works on the `0.1.0` tag.
* Operating System and version (iOS/macOS/Linux): macOS Monterey
* Xcode version (if applicable): Version 13.1 (13A1030d)
* Swift compiler version (if applicable): Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
* Swift Tools version (if applicable): Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)

## Reproduction Steps

* Check out the `main` branch of this repository locally.
* Change into the checked out directory.
* Run `xcrun swift package dump-package`

## Observed Behavior

The manifest fails to parse.

## Expected Behavior

The manifest parses successfully.

---

Thank you!

### LINKED ISSUE #620: Unpublished package does not work without extra setup
## Description
The AWS Swift SDK does not work when installed from the `main` branch unless significant local setup is performed (see the [steps](https://github.com/awslabs/aws-sdk-swift/blob/main/Package.swift#L20) listed in this repo's `Package.swift` file.)

It is desired that a tester could require this package like so:
```
.package(url: "https://github.com/awslabs/aws-sdk-swift.git", branch: "main")
```
and have it install from this repo's `main` branch, with the Swift SDK already generated, and dependencies `smithy-swift` and `aws-crt-swift` installed from their `main` branches, too.

## Context
This is causing difficulty for testers who are not Swift SDK developers, but are attempting to use & test unreleased changes to the SDK.

### PR DESCRIPTION
**Pull request by jbelkins**
## Issue \#
Fixes #505
Fixes #620 

## Description of changes

_Note: While in review, the following features are disabled/modified to simplify review & testing:_
- _Release and CI workflows are set to trigger on this branch only so they can be tested & demonstrated._
- _The full `release/` branch has not yet been merged back to this PR because it would severely clutter the diff below._
- _The release CI workflow does not yet commit changes back to its branch, for the same reason._
- _Release builds run with dependencies pointing to `main` instead of the last published version, else it would fail due to Endpoints 2.0 being merged since the last release._

_All of the above will be re-enabled before this PR merges._

_Also note: Seeing sporadic instances of [this bug](https://github.com/apple/swift-package-manager/issues/5767) when running `xcodebuild` on Xcode 14.  Building with Xcode 13 instead of 14 until this issue is fixed._

Simplifies the `Package.swift` and the rest of the project so that `main` can contain the latest release, eliminates several dependencies from CI builds, and enables all CI tasks to be run from the desktop (or any other machine).

Specific changes:
- `Package.swift` improvements:
  - The script that builds the `Package.swift` for this repo has been improved significantly, and is now the reference source of this package's manifest at all stages of the development cycle.
  - `Package.swift` can be generated to point to its dependencies using a published version, a branch, or a path.  This eliminates almost all need for special configuration on CI before dependency resolution, and allows devs to point to a local copy if desired.
  - Permits the latest release to be safely merged back to `main` since CI will no longer rely on special logic in `Package.swift`.
   - Eliminates the need for all hard-coded installation paths and CI-specific logic in `Package.swift`, allowing the generated `Package.swift` to be free of special configuration in all phases of the development cycle.
   - Developers can develop on the package either by using the "package edit mode" features provided by Xcode and Swift Package Manager, or the `Package.swift` can be generated with hard-coded local paths.
  - The separate `codegen/Package.swift` for protocol tests has been eliminated.  Instead, the main `Package.swift` may be optionally generated with protocol tests included.  (This is done automatically on CI before performing protocol tests.)

- CI simplification:
  - Eliminates the dependency on CRT's master build script.
  - Eliminates the dependency on CRT's Swift build container.
  - Linux builds are performed on "stock" Apple Swift docker containers; no container library / maintenance is required.
  - Eliminates the need for AWS credentials in the build process.
  - iOS & Mac platform builds are now performed using `xcodebuild` for an actual platform-native build.
  - Build steps have been extracted into scripts, allowing actions performed on CI to also be easily performed on development machines or as upstream/downstream jobs by other projects.
  - Preserves the ability for CI to automatically check out & build with the same branch name on `smithy-swift` and `aws-crt-swift` as the current branch for this repo.  Developer may also specify `smithy-swift` and `aws-crt-swift` branch names for development (not for releases) in the `versionDependencies.plist` file.

- Other:
  - The `release` CI action now builds the entire SDK and runs AWSClientRuntime tests before succeeding.  (This takes about 1hr 10mins on a Linux runner / Docker container, so I'm open to just running tests, or moving it to a macOS runner which has more CPU/RAM)
  - Moves instructions that were in `Package.swift` to the project's main `README.md`.
  - Moves `README` content that is relevant to integrators (i.e. just using the SDK & not code-generating) to the top of the file.
  - A couple `.gitignore` adds.

## New/existing dependencies impact assessment, if applicable
No new dependencies were added to this change.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: scripts/steps/build_and_test_with_xcodebuild.sh [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+# Create a temp dir for derived data (this seems to help
+# with certain spurious Xcode failures.)
+# Pipe the build logs through xcpretty.
+# On build failure, fail on Xcode's status code
+xcodebuild \
+  -scheme AWSSwiftSDK-Package \
+  -destination "$AWS_SDK_XCODEBUILD_DESTINATION" \
+  -derivedDataPath `mktemp -d` \
+  build test \
+  | xcpretty && exit ${PIPESTATUS[0]}
```
Comment (ganeshnj) [inline scripts/steps/build_and_test_with_xcodebuild.sh:22]: how is it made sure that you have xcpretty installed?

File: scripts/steps/install_dependencies.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+# When run on CI, set_references.sh should be run before this script.
+
+# Ensure release/ is present
+mkdir -p release
+
+# Generate Package.swift with branches set, if needed.
+swift ./scripts/generatePackageSwift.swift > Package.swift
+
+# Dump the manifest to the console
+cat Package.swift
```
Comment (ganeshnj) [inline scripts/steps/install_dependencies.sh:15]: I don't see service packages in the manifest here https://github.com/awslabs/aws-sdk-swift/actions/runs/3347731124/jobs/5546034658#step:7:2947

File: scripts/generatePackageSwift.swift [hunk 3]
```diff
@@ -5,33 +5,114 @@
...
+        ProtocolTest(name: "Ec2QueryTestSDK", path: "ec2-query", local: false),
+        ProtocolTest(name: "AWSQueryTestSDK", path: "aws-query", local: false),
+        //Service specific
+        ProtocolTest(name: "APIGatewayTestSDK", path: "apigateway", local: false),
+        ProtocolTest(name: "GlacierTestSDK", path: "glacier", local: false),
+        ProtocolTest(name: "MachineLearningTestSDK", path: "machinelearning", local: false),
+        ProtocolTest(name: "S3TestSDK", path: "s3", local: false),
+        //Local tests
+        ProtocolTest(name: "aws_restjson", path: "aws-restjson", local: true),
+        ProtocolTest(name: "rest_json_extras", path: "rest_json_extras", local: true),
```
Comment (ganeshnj) [inline scripts/generatePackageSwift.swift:74]: we must not hardcode these because they are dynamically generated and more can be added, this must done through reading the generated test packages

File: README.md [hunk 4]
```diff
@@ -13,8 +13,72 @@ This library is licensed under the Apache 2.0 License.
 [apache-badge]: https://img.shields.io/badge/License-Apache%202.0-blue.svg
 [apache-url]: LICENSE
 
+## Swift Package Manager Integration
```
Comment (ganeshnj) [inline README.md:16]: trivial: as you are editing this, restrict lines to 80-120 char limit

**Review by ganeshnj — CHANGES_REQUESTED** [review]

File: .github/workflows/continuous-integration.yml [hunk 5]
```diff
@@ -1,96 +1,77 @@
...
     runs-on: ubuntu-latest
     strategy:
       fail-fast: false
       matrix:
-        image:
-          - ubuntu-x64
-          - al2-x64
+        os:
+          - jammy
+          - amazonlinux2
```
Comment (ganeshnj) [inline .github/workflows/continuous-integration.yml:48]: could you add different archs here also
ie x86 and ARM

**Review by ganeshnj — CHANGES_REQUESTED** [review]

**Comment by ganeshnj** [comment]
Thanks for putting this up, nice work.

File: .github/workflows/continuous-integration.yml (hunk 5 above)
Comment (jbelkins) [reply .github/workflows/continuous-integration.yml:48]: I will have to see if Github has ARM Linux executors.  If they do, I will add

File: scripts/generatePackageSwift.swift (hunk 3 above)
Comment (jbelkins) [reply scripts/generatePackageSwift.swift:74]: They were hardcoded in the original `codegen/Package.swift`.  Was that file itself auto generated from somewhere?

File: scripts/steps/perform_release_codegen.sh [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+# install_dependencies_on_ci.sh should be run before this script.
+
+# Clear the contents of the release folder so it can be rebuilt clean
+rm -rf release/*
+
+# Build the SDK components
+./gradlew -p codegen/sdk-codegen build
+
+# Move SDK components into place
+./gradlew -p codegen/sdk-codegen stageSdks
```
Comment (ganeshnj) [inline scripts/steps/perform_release_codegen.sh:16]: thinking more into this, stageSdks should be the only task needed to tie things up. It must do the copying the SDK, merging models and generated the package.swift file.

This will make the developer feedback much faster, from the intellij, devs can build the codegen and stage. No other external commands are required.

Next commands would be just
swift build and swift test

**Review by ganeshnj — CHANGES_REQUESTED** [review]

**Comment by ganeshnj** [comment]
Things that we need to do fix main and make the experience better
- Rename `release` directory to `Source`
- Create `Tests` directory at root that contains the test packages which includes protocol and service tests

While we do this, individual `smithy-codegen` projects in build directory must stay workable.

File: scripts/generatePackageSwift.swift [hunk 7]
```diff
@@ -5,33 +5,114 @@
...
+}()
+
+struct ProtocolTest {
+    let name: String
+    let path: String
+    let local: Bool
 }
+
+let protocolBasePath = "./codegen/protocol-test-codegen/build/smithyprojections/protocol-test-codegen"
+let protocolBasePathLocal = "./codegen/protocol-test-codegen-local/build/smithyprojections/protocol-test-codegen-local"
```
Comment (ganeshnj) [inline scripts/generatePackageSwift.swift:55]: this generated package.swift must not know anything about codegen, here you are in a pure Swift world with no context about the codegen.

File: .github/workflows/continuous-integration.yml [hunk 8]
```diff
@@ -1,96 +1,77 @@
...
 
 jobs:
-  ios-compat:
+  apple-compat:
     runs-on: macos-12
+    strategy:
+      matrix:
+        destination:
+          - platform=iOS Simulator,OS=15.5,name=iPhone 13
+          - platform=macOS,arch=x86_64
```
[the remark this answers is not in the document]
Comment (jbelkins) [reply .github/workflows/continuous-integration.yml:17]: Not sure that Github has M1 Mac runners available.  We can at least build ARM code on an x86_64 and see that the build completes successfully.

File: .github/workflows/continuous-integration.yml [hunk 9]
```diff
@@ -1,96 +1,77 @@
...
-  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  AWS_REGION: us-east-1
-  AWS_SDK_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift
-  AWS_CRT_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/aws-crt-swift
-  SMITHY_SWIFT_CI_DIR: /Users/runner/work/aws-sdk-swift/aws-sdk-swift/target/build/deps/smithy-swift
+  push:
+    branches:
+      - jbe/improved_ci
+#  pull_request:
+#  workflow_dispatch:
```
[the remark this answers is not in the document]
Comment (jbelkins) [reply .github/workflows/continuous-integration.yml:8]: Yes, this is temporarily commented while this PR is in development

File: scripts/steps/build_and_test_with_xcodebuild.sh (hunk 1 above)
Comment (jbelkins) [reply scripts/steps/build_and_test_with_xcodebuild.sh:22]: It is installed on Github CI runners by default.  To run this on desktop, we can either require that developers install it (it is distributed as a Rubygem), or I can test for `xcpretty` and not pipe through it if it's not installed.

Xcode build logs are pretty unwieldy without it though (Github actually truncates our build logs if you don't use it), so probably better to require it to be installed.

File: .github/workflows/continuous-integration.yml (hunk 5 above)
Comment (jbelkins) [reply .github/workflows/continuous-integration.yml:48]: They do not.  We would have to self-host CI runners to build on ARM.

**Comment by jbelkins** [comment]
I am closing this PR but keeping the branch.  Rather than make all this change to the project & CI at once, we will do it on a more gradual basis.
