### ISSUE TITLE
Error parsing the Package.swift file

### ISSUE THREAD

**Issue by daveverwer** [awslabs/aws-sdk-swift#505]
## Description

Hello! I'm part of the [Swift Package Index](https://swiftpackageindex.com) team and was just trying to add this package to the index. We use `swift package dump-package` to extract package metadata in as JSON but when running that command for this package, the following error occurs:

```
$ xcrun swift package dump-package
/Users/dave/Desktop/aws-sdk-swift: error: manifest parse error(s):
main/Package.swift:104: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=260 "The folder “release” doesn’t exist." UserInfo={NSFilePath=/Users/dave/Projects/Amplify/SwiftSDK/aws-sdk-swift/release, NSUserStringVariant=(
    Folder
), NSUnderlyingError=0x600000a28090 {Error Domain=NSOSStatusErrorDomain Code=-43 "fnfErr: File not found"}}
error: invalid manifests at [<AbsolutePath:"/Users/dave/Desktop/aws-sdk-swift">]
```

This is broken on `main` but works on the `0.1.0` tag. Unfortunately, to add the package to the index we need to be able to initially run the `dump-package` on a checkout of the default branch.

## Environment

* AWS Swift SDK version used: This is broken on `main` but works on the `0.1.0` tag.
* Operating System and version (iOS/macOS/Linux): macOS Monterey
* Xcode version (if applicable): Version 13.1 (13A1030d)
* Swift compiler version (if applicable): Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
* Swift Tools version (if applicable): Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)

## Reproduction Steps

* Check out the `main` branch of this repository locally.
* Change into the checked out directory.
* Run `xcrun swift package dump-package`

## Observed Behavior

The manifest fails to parse.

## Expected Behavior

The manifest parses successfully.

---

Thank you!

**Comment by wooj2** [comment]
Hi @daveverwer,
By design, `main` branch is used for code generation source code.  The reason why the `main` branch has a `Package.swift` file is to facilitate local development of the SDKs (e.g, As a code generation developer, I can generate AWS SDKs on my dev machine, and execute them against local versions of the `AWSClientRuntime`, `ClientRuntime` and `CRT`), rather than public consumption.  There are currently no plans to support adding generated SDKs in the main branch.  Are there any work-arounds on your side to avoid pointing to `main`?

**Comment by daveverwer** [comment]
> Are there any work-arounds on your side to avoid pointing to `main`?

I've just done some investigation this afternoon on how our system would deal with a package with a broken manifest on the default branch and it's mixed news:

<img width="887" alt="Screenshot 2021-12-20 at 17 48 13@2x" src="https://user-images.githubusercontent.com/5180/146810277-2bf18283-0ef0-4145-98b2-42cb87c793f3.png">

Compared to this for your other package:

<img width="882" alt="Screenshot 2021-12-20 at 17 48 59@2x" src="https://user-images.githubusercontent.com/5180/146810359-45c7136a-5474-4913-afa3-cfd6018a679d.png">

One misleading bit from these screenshots is that we'd also be able to show a compatibility matrix for the package. That's missing here as I don't have the build system set up locally. However, that matrix would show that the main branch was broken across all Swift versions and platforms as those all fail to build due to the broken manifest. It would show the correct compatibility information for the tagged releases, though.

The good news is that some of the bits of information we can't get because of the broken manifest are just being omitted (dependency information, library/executable counts, etc...) and nothing is fundamentally broken. Others, like getting the version information and the fact that we never successfully "finish" processing the package are harder to fix. This means it would currently never appear in package search results.

It would be possible for us to start to work around some of these issues, but I'm not sure there are many occurrences of a package with an intentionally broken manifest, so it might not be a top priority.

I think the best solution, for now, is for it to stay out of the index. I'll leave it for you to decide whether to close this issue or not!

**Comment by ganeshnj** [comment]
Related https://github.com/awslabs/aws-sdk-swift/issues/620

**Comment by jbelkins** [comment]
@daveverwer Our default branch (`main`) should now build out-of-the-box without further config, so we're hoping that this package may now be successfully indexed.

We've submitted your form: https://github.com/SwiftPackageIndex/PackageList/issues/3058

We'll read the FAQ for Swift Package Index & do what's necessary to keep us listed & up-to-date.  Meanwhile, please let us know if there are any further issues with the intake of this package.  Thanks!

**Comment by daveverwer** [comment]
Thanks so much for this @jbelkins. So happy to have it in the index.

We're having some build machine issues at the moment (nothing to do with this package being added!) and so the build results aren't coming out quite right at the moment. I do believe that for your linux builds you'll need to use our base image that includes openssl via the `.spi.yml` file ([more information here](https://swiftpackageindex.com/swiftpackageindex/spimanifest/0.12.0/documentation/spimanifest/commonusecases#Images-for-Linux)). The build failures for the other platforms may be our issue, though. We're looking into it.

Thanks for adding your package to the project!
